name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Gerar animação Snake
        uses: Platane/snk@v3
        with:
          github_user_name: RanieuSousa
          outputs: |
            ./output/github-snake.svg
            ./output/github-snake-dark.svg

      - name: Fazer deploy no branch output
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_branch: output
          publish_dir: ./output
